name: docker workflow
on:
  workflow_dispatch:

jobs:    
  docker-build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4.2.2
       - name: Docker Setup Docker
         uses: docker/setup-docker-action@v4.3.0
       - name: Docker build
         run: |
           docker build -t docker-node-app .
